### ISSUE TITLE
Train/Test Speed

### ISSUE THREAD

**Issue by wk910930** [jaxony/ShuffleNet#2]
Dear @jaxony ,

Thanks for your work!

I am using [this](https://github.com/pytorch/examples/tree/master/imagenet) to train ShuffleNet on ImageNet. However, both training and testing speed looks very slow.

ShuffleNet at epoch 2:
```
Test: [190/196] Time 3.673 (3.323)      Loss 2.3073 (3.7287)    Prec@1 43.750 (24.235)  Prec@5 75.000 (47.801)
```
While for AlexNet at epoch 2:
```
Test: [190/196] Time 0.672 (0.558)      Loss 3.7238 (4.3975)    Prec@1 28.125 (15.122)  Prec@5 50.391 (35.214)
```

ShuffleNet is about 6 times slower than AlexNet. Have you noticed this on MNIST?

Thanks!
Kun

**Comment by jaxony** [comment]
Hi @wk910930, thanks for bringing this up! I have a feeling it has to do with an unoptimized implementation of depth-wise convolutions (DWCs) in PyTorch. I'll take a look into this when I get a chance, but here is a related issue you can read up on: https://github.com/pytorch/pytorch/issues/1708. 

According to this issue, DWCs are slow in PyTorch. Maybe we have to wait till PyTorch releases a more efficient implementation of DWCs.

**Comment by wk910930** [comment]
Now I see. Thanks again! Closing the issue.
