### ISSUE TITLE
When group=8, input channels cannot be divided by group number

### ISSUE THREAD

**Issue by xmfbit** [jaxony/ShuffleNet#5]
Hi, when I run your code when `group = 8`, the error occurs that `ValueError: in_channels must be divisible by groups`.
According to the paper, I think there is no problem with your implementation. Do you have tested your code using `group = 8`?
By the way, there is the same problem when I tried to build ShuffleNet0.5x using `scale=0.5`.
To reproduce the issue, just modify `groups=3` to `groups=8` here: https://github.com/jaxony/ShuffleNet/blob/master/tests.py#L104

**Comment by jaxony** [comment]
@xmfbit Thanks for bringing this bug to my attention. I've fixed it up now. Turns out all it took was one line haha. Let me know if there are any other issues with the grouping. I haven't tested changing the scale though.

**Comment by xmfbit** [comment]
Yes. I think current implementation is right. -in_channels only occurs in the last 1x1 conv. Glad to help you and your code helped me a lot. Thanks.
