### ISSUE TITLE
Pretrained Model Cannot Be Opened

### ISSUE THREAD

**Issue by makeecat** [jaxony/ShuffleNet#9]
The tar file you provided can not be opened.
Could you provide us your raw pth file?

**Comment by jaxony** [comment]
Hi @makeecat, do you mind sharing some code on how you are opening the `.pth` file? I've had no problems opening the pretrained weights: https://github.com/jaxony/ShuffleNet/blob/master/infer.py#L36

**Comment by makeecat** [comment]
The tar file shufflenet.pth.tar can not be opened by `tar -xvf shufflenet.pth.tar`

**Comment by jaxony** [comment]
Hmm usually you can just open `.tar` and `.pth` files with `torch.load()`, so you don't need to extract it yourself on the cmdline with `tar` command. `shufflenet.pth.tar` might also be a `.pth` file, so that's probably why you get that error.
